# Generated by Django 5.1.5 on 2025-10-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depto',
            name='empleados',
            field=models.ManyToManyField(related_name='empleado', to='user.user'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='deptos',
            field=models.ManyToManyField(to='empresa.depto'),
        ),
    ]
